# Generated by Django 4.1 on 2022-09-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=60)),
                ('rubro', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('instagram', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
