# Generated by Django 4.1 on 2022-10-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_datos_alter_personas_fecha_nacimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datos',
        ),
        migrations.AlterField(
            model_name='personas',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
