# Generated by Django 4.1 on 2022-10-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cosas'),
        ),
    ]
