# Generated by Django 4.1 on 2022-10-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_data_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Avatar', 'verbose_name_plural': 'Avatares'},
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
