# Generated by Django 4.1 on 2022-10-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_remove_data_image_data_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empleos',
        ),
        migrations.DeleteModel(
            name='informacion',
        ),
        migrations.DeleteModel(
            name='personas',
        ),
    ]
