# Generated by Django 4.1 on 2022-10-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_delete_empleos_delete_informacion_delete_personas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='entregable',
        ),
        migrations.DeleteModel(
            name='familia',
        ),
    ]
